config/routes.rb
Yacto::Application.routes.draw do

  resources :error_messages

  get 'cities/search' => "cities#search"
  resources :cities

  resources :countries

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations" ,:omniauth_callbacks => "omniauth_callbacks"} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
    get '/users/sign_out' => "devise/sessions#destroy"
   
  end
  get "users/session_user"
  get "users/get_session"
  get "offers/dashboard"
  get "start_page/index"
  get "start_page/index3"
  get "start_page/offer"
  get "start_page/page03"
  get "start_page/offer03"
	%w(about_us blog contact_us our_partners terms_and_conditions privacy business_owners how_it_works_merchants how_it_works_consumers).each	do |page|
		get page,  :controller => "static_pages",:action => page
	end

  get "home/ajax_twitter_on"
  get "home/ajax_twitter_off"
  get "home/ajax_gplus_on"
  get "home/ajax_gplus_off"
  get "home/ajax_facebook_on"
  get "home/ajax_facebook_off"
	get "home/about_us"
  get "offers/ajax_favorite"
  get "offers/ajax_unfavorite"
  get "merchants/ajax_favorite"
  get "merchants/ajax_unfavorite"
  get "offers/ajax_lonlat"
  get "offers/require_sign_in"
  post "home/lookup_address"
  post "offers/unique_email"
  post "offers/create_offer"
  post "offers/get_google_places"
  post "offers/get_business_detail"
  post "offers/post_social_network_offer"
  post "offers/post_persional_detail"
  get 'home/autocomplete'
  get 'home/autocomplete_address'
  get "offers/filter_to_offers"
  get 'offers/redirect_to_offers'
  get 'offers/get_more_product'
  get 'offers/filter'
  get "merchants/sms_request"
  get "merchant_types/top_lvl"
  get 'offers/list_detail'
  get "merchants/call"
  get "offers/nearby"
  get "offers/ajax_time"
  get "offers/ajax_distance"
  get "offers/ajax_offer_group"
  get "offers/set_location"
  get "merchants/survey"
  get "merchants/survey_city"
  get "merchants/survey_source"
  post "merchants/search_google_place"
  match "merchants/admin" => "merchants#admin"

  put 'users/generate_code/:id' => "users#generate_code"
  put 'offers/update_repeat_day/:id' => "offers#update_repeat_day"
  put 'offers/update_local_end_day/:id' => "offers#update_local_end_day"
  put 'merchants/update_repeat_merchant/:id' => "merchants#update_repeat_merchant"
  put 'merchants/update_active/:id' => "merchants#update_active"
  put 'offers/update_merchant_type/:id' => 'offers#update_merchant_type'

  put "users/account_setting/:id"  => "users#account_setting"

  match "users/show" => "users#show"

  resources :offers, :offer_insertions, :merchant_types

  resource :location, :only => [:show]
  resources :favorites, :only => [:create, :index, :destroy]

  resource :dashboard, :only => [:show] do
    get "offers", :on => :member
  end

  resource :bb, :only => :show, :controller => "backbone"

  resources :merchants do
    collection do
      post  "search"
      post "sms_request"
     
    end
  end
  match ':merchant_id' => "users#index", :as => :merchant_details
  
  resources :users do
    member do
      get "toggle_offer", "change_recurrence"
      
    end
    collection do
      get "ajax_sub_types"
      post "new_employee"
      post "new_merchant_offer"
    end
  end

  root :to => 'home#index'
  get "home/index"
  resources :merchant_photos

end

app/models/offer_insertion.rb
class OfferInsertion < ActiveRecord::Base
  validates :name, :length => { :maximum => 140 }
  attr_accessible :name
end
# == Schema Information
#
# Table name: offer_insertions
#  t.string   "name"
#  t.datetime "created_at", :null => false
#  t.datetime "updated_at", :null => false

app/controllers/offer_insertions_controller.rb
class OfferInsertionsController < ApplicationController
  load_and_authorize_resource

  # GET /offer_insertions
  # GET /offer_insertions.json
  def index
    @offer_insertions = OfferInsertion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offer_insertions }
    end
  end

  # GET /offer_insertions/1
  # GET /offer_insertions/1.json
  def show
    @offer_insertion = OfferInsertion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer_insertion }
    end
  end

  # GET /offer_insertions/new
  # GET /offer_insertions/new.json
  def new
    @offer_insertion = OfferInsertion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer_insertion }
    end
  end

  # GET /offer_insertions/1/edit
  def edit
    @offer_insertion = OfferInsertion.find(params[:id])
  end

  # POST /offer_insertions
  # POST /offer_insertions.json
  def create
    @offer_insertion = OfferInsertion.new(params[:offer_insertion])

    respond_to do |format|
      if @offer_insertion.save
        format.html { redirect_to @offer_insertion, notice: t('offerinsertion.create') }
        format.json { render json: @offer_insertion, status: :created, location: @offer_insertion }
      else
        format.html { render action: "new" }
        format.json { render json: @offer_insertion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offer_insertions/1
  # PUT /offer_insertions/1.json
  def update
    @offer_insertion = OfferInsertion.find(params[:id])

    respond_to do |format|
      if @offer_insertion.update_attributes(params[:offer_insertion])
        format.html { redirect_to @offer_insertion, notice: t('offerinsertion.update') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer_insertion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offer_insertions/1
  # DELETE /offer_insertions/1.json
  def destroy
    @offer_insertion = OfferInsertion.find(params[:id])
    @offer_insertion.destroy

    respond_to do |format|
      format.html { redirect_to offer_insertions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offer_insertions_helper.rb
module OfferInsertionsHelper
end

app/views/offer_insertions/_form.html.erb
<%= form_for(@offer_insertion) do |f| %>
  <% if @offer_insertion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer_insertion.errors.count, "error") %> <%= t("form.errorswithclass", :class => 'offer_insertion') %></h2>

      <ul>
      <% @offer_insertion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offer_insertions/edit.html.erb
<h1><%= t("form.editingclass", :class => "offer_insertion") %></h1>

<%= render 'form' %>

<%= link_to t("form.show"), @offer_insertion %> |
<%= link_to t("form.back"), offer_insertions_path %>

app/views/offer_insertions/index.html.erb
<h1><%= t("form.listingclass", :class => "offer_insertions") %></h1>

<table>
  <tr>
    <th><%= t("offerinsertion.name") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offer_insertions.each do |offer_insertion| %>
  <tr>
    <td><%= offer_insertion.name %></td>
    <td><%= link_to t("form.show"), offer_insertion %></td>
    <td><%= link_to t("form.edit"), edit_offer_insertion_path(offer_insertion) %></td>
    <td><%= link_to t("form.destroy"), offer_insertion, confirm: t("form.confirmdelete"), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t("form.newclass", :class => "Offer insertion"), new_offer_insertion_path %>

app/views/offer_insertions/new.html.erb
<h1><%= t("form.newclass", :class => "offer_insertion") %></h1>

<%= render 'form' %>

<%= link_to t("form.back"), offer_insertions_path %>

app/views/offer_insertions/show.html.erb
<p>
  <b><%= t("offerinsertion.name") %>:</b>
  <%= @offer_insertion.name %>
</p>


<%= link_to t("form.edit"), edit_offer_insertion_path(@offer_insertion) %> |
<%= link_to t("form.back"), offer_insertions_path %>