config/routes.rb
Yacto::Application.routes.draw do

  resources :error_messages

  get 'cities/search' => "cities#search"
  resources :cities

  resources :countries

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations" ,:omniauth_callbacks => "omniauth_callbacks"} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
    get '/users/sign_out' => "devise/sessions#destroy"
   
  end
  get "users/session_user"
  get "users/get_session"
  get "offers/dashboard"
  get "start_page/index"
  get "start_page/index3"
  get "start_page/offer"
  get "start_page/page03"
  get "start_page/offer03"
	%w(about_us blog contact_us our_partners terms_and_conditions privacy business_owners how_it_works_merchants how_it_works_consumers).each	do |page|
		get page,  :controller => "static_pages",:action => page
	end

  get "home/ajax_twitter_on"
  get "home/ajax_twitter_off"
  get "home/ajax_gplus_on"
  get "home/ajax_gplus_off"
  get "home/ajax_facebook_on"
  get "home/ajax_facebook_off"
	get "home/about_us"
  get "offers/ajax_favorite"
  get "offers/ajax_unfavorite"
  get "merchants/ajax_favorite"
  get "merchants/ajax_unfavorite"
  get "offers/ajax_lonlat"
  get "offers/require_sign_in"
  post "home/lookup_address"
  post "offers/unique_email"
  post "offers/create_offer"
  post "offers/get_google_places"
  post "offers/get_business_detail"
  post "offers/post_social_network_offer"
  post "offers/post_persional_detail"
  get 'home/autocomplete'
  get 'home/autocomplete_address'
  get "offers/filter_to_offers"
  get 'offers/redirect_to_offers'
  get 'offers/get_more_product'
  get 'offers/filter'
  get "merchants/sms_request"
  get "merchant_types/top_lvl"
  get 'offers/list_detail'
  get "merchants/call"
  get "offers/nearby"
  get "offers/ajax_time"
  get "offers/ajax_distance"
  get "offers/ajax_offer_group"
  get "offers/set_location"
  get "merchants/survey"
  get "merchants/survey_city"
  get "merchants/survey_source"
  post "merchants/search_google_place"
  match "merchants/admin" => "merchants#admin"

  put 'users/generate_code/:id' => "users#generate_code"
  put 'offers/update_repeat_day/:id' => "offers#update_repeat_day"
  put 'offers/update_local_end_day/:id' => "offers#update_local_end_day"
  put 'merchants/update_repeat_merchant/:id' => "merchants#update_repeat_merchant"
  put 'merchants/update_active/:id' => "merchants#update_active"
  put 'offers/update_merchant_type/:id' => 'offers#update_merchant_type'

  put "users/account_setting/:id"  => "users#account_setting"

  match "users/show" => "users#show"

  resources :offers, :offer_insertions, :merchant_types

  resource :location, :only => [:show]
  resources :favorites, :only => [:create, :index, :destroy]

  resource :dashboard, :only => [:show] do
    get "offers", :on => :member
  end

  resource :bb, :only => :show, :controller => "backbone"

  resources :merchants do
    collection do
      post  "search"
      post "sms_request"
     
    end
  end
  match ':merchant_id' => "users#index", :as => :merchant_details
  
  resources :users do
    member do
      get "toggle_offer", "change_recurrence"
      
    end
    collection do
      get "ajax_sub_types"
      post "new_employee"
      post "new_merchant_offer"
    end
  end

  root :to => 'home#index'
  get "home/index"
  resources :merchant_photos

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'geokit'
  include Geokit::Geocoders
  def index
    if request.format == :mobile 
      redirect_to bb_url(:anchor=>"filters")
    end
  end
  
  def ajax_twitter_on
    cookies[:twitter_on] = true
    render :text => 'on'
  end
  
  def ajax_twitter_off
    cookies[:twitter_on] = false
    render :text => 'off'
  end
  def ajax_gplus_on
    cookies[:gplus_on] = true
    render :text => 'on'
  end

  def ajax_gplus_off
    cookies[:gplus_on] = false
    render :text => 'off'
  end
  def ajax_facebook_on
    cookies[:facebook_on] = true
    render :text => 'on'
  end
  
  def ajax_facebook_off
    cookies[:facebook_on] = false
    render :text => 'off'
  end
      
  def lookup_address
    res = ","
    begin
      loc=GoogleGeocoder.geocode(params[:address])
      if loc.success
        res= loc.lat.to_s + "," + loc.lng.to_s
      end
    rescue
    end
    if res == ","
      render :text => "not found", :status => 500
    else
      render :text => "#{(res.split(",")).to_json}"
    end
  end
  def autocomplete
    
    @cities = City.all(:joins => :country, :conditions => ["lower(cast(cities.name || cast(' ' AS varchar) || countries.name AS varchar)) LIKE ?", "#{params[:term].downcase}%"],:order => 'cities.name, countries.name asc', :limit => 10)
    @cities.collect! {|item| {:label => item.name + " " + item.country.name, :id => item.id,:country => item.country.name}}
    render :json => @cities
  end
  def autocomplete_address
    @address = Merchant.find(:all, :conditions => ['lower(primary_address) LIKE ?', "%#{params[:term].downcase}%"],:order => 'primary_address asc', :limit => 5)
    @address.collect! {|item| {:label => item.primary_address, :id => item.id}}
    render :json => @address
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= javascript_include_tag "jquery-checkbox-switch" %>
<script type="text/javascript">

  $(document).ready(function (){
    $("#twitter_on").CheckboxSwitch();
    $("#facebook_on").CheckboxSwitch();
  });
</script>

<h1>Home</h1>
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>
<% if user_signed_in? %>
  <div id="user_login_box" style="float:right">
    <%= current_user.username ? current_user.username : current_user.username %> |
    <%= link_to t("form.myinfo"), edit_user_registration_path %> |
    <%= link_to t("form.signout"), destroy_user_session_path,  :method => :delete  %>
  </div>
<% end %>
<% unless user_signed_in? -%>
  <p><%= link_to t("form.signup"), new_user_registration_path %></p>
  <p><%= link_to t("form.signin"), new_user_session_path %></p>

<% end -%>
<% if current_user and current_user.merchant == nil %>
<%= link_to "You are Merchant?",new_merchant_path %>
<% elsif current_user and current_user.merchant  %>
  <%= link_to "My Merchant",current_user.merchant %>
<% end %>
<% if current_user and current_user.merchant != nil %>
<%= link_to "New Offer",new_offer_path %>
<% end %>
<%= link_to "Offer list",offers_path, "data-ajax" => "false" %>
<br/>
<%= link_to t("form.signinwithname", :name => 'Twitter'), user_omniauth_authorize_path(:twitter)  %>
<%= link_to t("form.signinwithname", :name => 'Facebook'), user_omniauth_authorize_path(:facebook) %>
<%= link_to t("form.signinwithname", :name => 'Google'), user_omniauth_authorize_path(:google_oauth2) %>
<%= link_to t("form.signinwithname", :name => 'Yahoo'), user_omniauth_authorize_path(:yahoo) %>
<%#= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter),:onclick => "window.open(this.href,'Sign in with Twitter', 'height=500, width=500');return false;"  %>
<%#= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook),:onclick => "window.open(this.href,'Sign in with Facebook', 'height=500, width=500');return false;"  %>
<%#= link_to "Sign in with Google", user_omniauth_authorize_path(:google),:onclick => "window.open(this.href,'Sign in with Google', 'height=500, width=600');return false;"  %>
<br/>
<% if current_user and current_user.merchant == nil %>
<%= link_to "You are Merchant?",new_merchant_path %>
<% end %>
<% if current_user and current_user.merchant != nil %>
<%= link_to "New Offer",new_offer_path %>
<% end %>
<br/>
<%= t("form.posttoname", :name => 'Twitter') %> <%= check_box_tag 'twitter_on' %>
<%= t("form.posttoname", :name => 'Facebook') %> <%= check_box_tag 'facebook_on' %>
<%= hidden_field_tag 'hidden_twitter',  cookies[:twitter_on], :id => 'hidden_twitter' %>
<%= hidden_field_tag 'hidden_facebook', cookies[:facebook_on], :id => 'hidden_facebook'%>

app/views/home/index.mobile.erb
<div data-role="page" id="indexPage">
  <script>
    $(document).bind("mobileinit", function(){
      //Disable ajax link
      $('.disable-ajax').click(function(event){
        $.mobile.ajaxFormsEnabled = false;
      });
    });
  </script>
  <script type="text/javascript" >
    $("#twitter_on option[value='twitter_on']").attr("selected", "selected");
  </script>

  <div data-role="header" data-theme="e" style="height: 42px;">
    <a href="offers/set_location"  data-rel="dialog" data-theme="a" data-inline="true" id="filter_dialog" data-ajax="false"> Set Location</a>
    <h1>Yacto</h1>
  </div>
 

  
  <% if user_signed_in? %>
    <div id="user_login_box_mobile">
      <%= current_user.username ? current_user.username : current_user.username %> |
      <%= link_to t('home.index.my_info'), edit_user_registration_path,"data-ajax" => "false" %> |
      <%= link_to t('home.index.sign_out'), destroy_user_session_path,"data-ajax" => "false", :method => :delete %>
    </div>
  <% end %>
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>
  <% if current_user and current_user.merchant == nil %>
    <%= link_to "You are Merchant?",new_merchant_path %>
  <% elsif current_user and current_user.merchant  %>
    <%= link_to "My Merchant",current_user.merchant, :rel => "external" %>
  <% end %>
  <% if current_user and current_user.merchant != nil %>
    <%= link_to "New Offer",new_offer_path %>
  <% end %>
  <%= render :partial => "shared/nav_home" %>
  <div style="width: 100%; text-align: center; padding-top: 20px;">
    <%=t 'home.index.create_an_account' %>
  </div>

  <div  style="padding-left: 10px;padding-right: 10px; margin-bottom: 10px;">
    <ul data-role="listview" data-inset="true" style="margin-top: 20px;margin-bottom: 10px;border-radius:10px;">
      <li><%= image_tag("mobile/twitter.png",:class => "icon_fb_tw") %><%= link_to t('home.index.sign_in_with')+ " Twitter", user_omniauth_authorize_path(:twitter),:rel => "external","data-ajax" => "false" %></li>
      <li><%= image_tag("mobile/facebook.png",:class => "icon_fb_tw") %><%= link_to t('home.index.sign_in_with')+ " Facebook", user_omniauth_authorize_path(:facebook) ,:rel => "external","data-ajax" => "false"%></li>
      <li><%= image_tag("mobile/google.png",:class => "icon_email") %><%= link_to t('home.index.sign_in_with')+ " Google", user_omniauth_authorize_path(:google_oauth2),:rel => "external","data-ajax" => "false" %></li>
       <% if current_user.nil? %>
      <li><%= image_tag("mobile/email.png",:class => "icon_email") %><%= link_to t('home.index.sign_in_with')+ " Email", new_user_session_path %></li>
      <% end %>
    </ul>
    <% unless user_signed_in? -%>
      <p><%= link_to t("form.signup"), new_user_registration_path %></p>
    <% end -%>
    <div class="box_line">
      <label for="twitter_on" style="padding-top: 10px; float: left;padding-right: 10px"><%= t('home.index.post_to')+' Twitter' %></label>
      <select name="twitter_on" id="twitter_on" data-role="slider" style="float: right;height: 47px; width: 100px;">
        <option value="off"><%= t('home.index.off')%></option>
        <% if cookies[:twitter_on] == true %>
          <option value="on" selected="true" >On</option>
        <% else %>
          <option value="on"><%= t('home.index.on')%></option>
        <% end %>
      </select>
    </div>

    <div class="box_line">
      <label for="facebook_on" style="padding-top: 10px; float: left;padding-right: 10px"><%= t('home.index.post_to')+' Facebook' %></label>
      <select name="facebook_on" id="facebook_on" data-role="slider" style="float: right;height: 47px; width: 100px;">
        <option value="off"><%= t('home.index.off')%></option>
        <% if cookies[:facebook_on] == true %>
          <option value="on" selected="true" ><%= t('home.index.on')%></option>
        <% else %>
          <option value="on"><%= t('home.index.on')%></option>
        <% end %>
      </select>
    </div>

    <div class="box_line">
      <label for="google_on" style="padding-top: 10px; float: left;padding-right: 10px"><%= t('home.index.post_to')+' Google+' %></label>
      <select name="google_on" id="google_on" data-role="slider" style="float: right;height: 47px; width: 100px;">
        <option value="off"><%= t('home.index.off')%></option>
        <% if cookies[:google_on] == true %>
          <option value="on" selected="true" ><%= t('home.index.on')%></option>
        <% else %>
          <option value="on"><%= t('home.index.on')%></option>
        <% end %>
      </select>
    </div>
    <%= hidden_field_tag 'hidden_twitter',cookies[:twitter_on] %>
    <%= hidden_field_tag 'hidden_facebook',cookies[:facebook_on] %>
    <%= hidden_field_tag 'hidden_google',cookies[:google_on] %>
  </div>

  <script type="text/javascript">

    $('.ui-li.ui-btn').live('click', function () {
      var link = $(this).find('a:first');
      if (link) {
        if ($(link).attr('data-ajax') == "false") {
          document.location = $(link).attr('href').toString();
        } else {
          $.mobile.changePage($(link).attr('href').toString());
        }
      }
    });

    $('.ui-btn-back').live('tap', function () {
      history.back(); return false;
    }).live('click', function () {
      history.back(); return false;
    });

    $('[data-role=page]').live('pageshow', function (event, ui) {
      if ($('[bodyclass]:first').length == 1) {
        $('body').addClass($('[bodyclass]').attr('bodyclass'));
      }

      var url = window.location.toString();
      var hashLocation = url.indexOf("#");
      if (hashLocation != -1) {
        url = url.substring(hashLocation + 1);
      }
      else {
        url = window.location.pathname.toString();
      }

      try {
        var pageTracker = _gat._getTracker("UA-212043-6");
        pageTracker._trackPageview(url);
      } catch (err) { }

      if ($('div.gallery-page').length == 1) {
        $("ul.gallery a").photoSwipe(
        {
          allowUserZoom: false,
          jQueryMobile: true,
          autoStartSlideshow: false,
          backButtonHideEnabled: false,
          captionAndToolbarAutoHideDelay: 0,
          preventSlideshow: true
        });
      }
    });  

  </script>
  <script type="text/javascript">

    var mobileDemo = { 'center': '57.7973333,12.0502107', 'zoom': 5 };
    $('#indexPage').live('pageinit', function() {
      demo.add('indexPage', function() {

        $('#map_canvas_2').gmap({'center': mobileDemo.center, 'zoom': 5 , 'disableDefaultUI':true, 'callback': function(map) {
            var self = this;
            self.watchPosition(function(position, status) {
              if ( status === 'OK' ) {
      
                var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                $.ajax({
                  type: "GET",
                  url: "<%= offers_ajax_lonlat_path %>",
                  data: "lon=" +  position.coords.longitude + "&lat=" + position.coords.latitude,

                  success: function(data){
                      
                    return false;
                  },
                  error: function(msg){
 
                    alert('<%= t("set_location.error") %>');
                    window.location.replace('<%= url_for(:controller => 'offers', :action => 'set_location')%>');
                    return true;
                  }
                  
                });
                if ( !self.get('markers').client ) {
                  self.addMarker({ 'id': 'client', 'position': latlng, 'bounds': true });
                } else {
                  self.get('markers').client.setPosition(latlng);
                  //-try to add circle for mobile---self.set('clientPosition', new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
                  //-try to add circle for mobile---self.addShape('Circle', { 'strokeWeight': 0, 'fillColor': "#008595", 'fillOpacity': 0.25, 'center': self.get('clientPosition'), 'radius': 15, clickable: false });
                  map.panTo(latlng);
                }
              } 
            });
         
          }});
        
      }).load('indexPage');
      
    });


			

  </script>

  <div id="map_canvas_2" style="height:0px;"></div>
</div>