config/routes.rb
Yacto::Application.routes.draw do

  resources :error_messages

  get 'cities/search' => "cities#search"
  resources :cities

  resources :countries

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations" ,:omniauth_callbacks => "omniauth_callbacks"} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
    get '/users/sign_out' => "devise/sessions#destroy"
   
  end
  get "users/session_user"
  get "users/get_session"
  get "offers/dashboard"
  get "start_page/index"
  get "start_page/index3"
  get "start_page/offer"
  get "start_page/page03"
  get "start_page/offer03"
	%w(about_us blog contact_us our_partners terms_and_conditions privacy business_owners how_it_works_merchants how_it_works_consumers).each	do |page|
		get page,  :controller => "static_pages",:action => page
	end

  get "home/ajax_twitter_on"
  get "home/ajax_twitter_off"
  get "home/ajax_gplus_on"
  get "home/ajax_gplus_off"
  get "home/ajax_facebook_on"
  get "home/ajax_facebook_off"
	get "home/about_us"
  get "offers/ajax_favorite"
  get "offers/ajax_unfavorite"
  get "merchants/ajax_favorite"
  get "merchants/ajax_unfavorite"
  get "offers/ajax_lonlat"
  get "offers/require_sign_in"
  post "home/lookup_address"
  post "offers/unique_email"
  post "offers/create_offer"
  post "offers/get_google_places"
  post "offers/get_business_detail"
  post "offers/post_social_network_offer"
  post "offers/post_persional_detail"
  get 'home/autocomplete'
  get 'home/autocomplete_address'
  get "offers/filter_to_offers"
  get 'offers/redirect_to_offers'
  get 'offers/get_more_product'
  get 'offers/filter'
  get "merchants/sms_request"
  get "merchant_types/top_lvl"
  get 'offers/list_detail'
  get "merchants/call"
  get "offers/nearby"
  get "offers/ajax_time"
  get "offers/ajax_distance"
  get "offers/ajax_offer_group"
  get "offers/set_location"
  get "merchants/survey"
  get "merchants/survey_city"
  get "merchants/survey_source"
  post "merchants/search_google_place"
  match "merchants/admin" => "merchants#admin"

  put 'users/generate_code/:id' => "users#generate_code"
  put 'offers/update_repeat_day/:id' => "offers#update_repeat_day"
  put 'offers/update_local_end_day/:id' => "offers#update_local_end_day"
  put 'merchants/update_repeat_merchant/:id' => "merchants#update_repeat_merchant"
  put 'merchants/update_active/:id' => "merchants#update_active"
  put 'offers/update_merchant_type/:id' => 'offers#update_merchant_type'

  put "users/account_setting/:id"  => "users#account_setting"

  match "users/show" => "users#show"

  resources :offers, :offer_insertions, :merchant_types

  resource :location, :only => [:show]
  resources :favorites, :only => [:create, :index, :destroy]

  resource :dashboard, :only => [:show] do
    get "offers", :on => :member
  end

  resource :bb, :only => :show, :controller => "backbone"

  resources :merchants do
    collection do
      post  "search"
      post "sms_request"
     
    end
  end
  match ':merchant_id' => "users#index", :as => :merchant_details
  
  resources :users do
    member do
      get "toggle_offer", "change_recurrence"
      
    end
    collection do
      get "ajax_sub_types"
      post "new_employee"
      post "new_merchant_offer"
    end
  end

  root :to => 'home#index'
  get "home/index"
  resources :merchant_photos

end

app/models/merchant_type.rb
class MerchantType < ActiveRecord::Base

#  validates :merchant_type, :inclusion => { :in => %w(Eat Drink Fun Look Services Shoping Travel Other),
#    :message => "%{value} is not a valid type" },

#    :length => { :maximum => 20 }
##  validates :sub_type, :inclusion => { :in => %w(Chinese Sushi Other),
##    :message => "%{value} is not a valid sub type" },
##    :length => { :maximum => 20 }
#  validates :language, :inclusion => { :in => %w(USEnglish UKEnglish German Swedish),
#    :message => "%{value} is not a valid language" },
#    :length => { :maximum => 30 }
  has_many :offers
  #belongs_to :user
  has_many :merchants
  attr_accessible :merchant_type, :sub_type, :language, :lookup_item_id,:color,
    :image, :marker_image, :map_icon

  scope :merchant_type, lambda {|type| where(:merchant_type => type) }
  scope :top_lvl, where(:sub_type => " ")
  #  validate :type_included, :sub_type_included, :language_included
  #  def type_included
  #    unless ["Eat", "Drink", "Fun", "Do", "Other"].include? type
  #      errors.add(:type, "type is not valid")
  #    end
  #  end
  #  def sub_type_included
  #    unless ["Chinese", "Sushi"].include? sub_type
  #      errors.add(:type, "sub_type is not valid")
  #    end
  #  end
  #  def language_included
  #    unless ["USEnglish", "UKEnglish", "German", "Swedish"].include? language
  #      errors.add(:type, "language is not valid")
  #    end
  #  end
end

# == Schema Information
#
# Table name: merchant_types
#  t.string   "language"
#  t.string   "lookup_item_id"
#  t.string   "merchant_type"
#  t.string   "sub_type"
#  t.datetime "created_at",     :null => false
#  t.datetime "updated_at",     :null => false

app/controllers/merchants_controller.rb
# encoding: utf-8
require 'phony'
require 'open-uri'
require 'net/http'
class MerchantsController < ApplicationController
  include Geokit::Geocoders
  # load_and_authorize_resource
  # GET /merchants
  # GET /merchants.json
  def index
    query_string = ""
    conditions = {}
    if params[:merchant]
      if params[:merchant][:merchant_id] != nil and params[:merchant][:merchant_id] != ''
        query_string = query_string + " AND UPPER(merchants.merchant_id) LIKE :merchant_id"
        conditions[:merchant_id] = "%" + params[:merchant][:merchant_id].strip.upcase + "%"
      end
      if params[:merchant][:name] != nil and params[:merchant][:name] != ''
        query_string = query_string + " AND UPPER(merchants.name) LIKE :name"
        conditions[:name] = "%" + params[:merchant][:name].strip.upcase + "%"
      end
      if params[:merchant][:mobile_number] != nil and params[:merchant][:mobile_number] != ''
        query_string = query_string + " AND UPPER(merchants.mobile_number) LIKE :mobile_number"
        conditions[:mobile_number] = "%" + params[:merchant][:mobile_number].strip.upcase + "%"
      end
      if params[:merchant][:primary_address] != nil and params[:merchant][:primary_address] != ''
        query_string = query_string + " AND UPPER(merchants.primary_address) LIKE :primary_address"
        conditions[:primary_address] = "%" + params[:merchant][:primary_address].strip.upcase + "%"
      end
    end
    query_string = query_string + " AND countries.id = :country"
    params[:country] = Country.find_by_name("United States").id if params[:country].nil?
    puts params
    conditions[:country] = params[:country].to_i
    @merchants = Merchant.joins({:city => :country}).where("created_at is not NULL" + query_string,  conditions).paginate(:page => params[:page],:per_page =>  15).order("created_at DESC")
   #@merchants = Merchant.find(:all,:joins => {:city => :country}, :conditions =>(:contries))
    respond_to do |format|
      format.html # index.html.erb
      format.mobile
      format.json { render :json => @merchants }
    end
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    if session[:current_location] == nil
      session[:current_location] = current_location(nil,nil, cookies)
    end
    if session[:timezone] == nil
      set_country_and_timezone(session[:current_location])
    end
    if session[:timezone]
      tz = TZInfo::Timezone.get(session[:timezone])
      @now_time = tz.utc_to_local(Time.current)
    end
    @res = session[:current_location]
    if @res
      @current_location = @res.full_address
    end
    puts params
    @merchant = Merchant.find(params[:id])

    @offers_mon = @merchant.offers.active.monday_offers.order('created_at asc').to_a 
    @offers_tue = @merchant.offers.active.tuesday_offers.order('created_at asc').to_a
    @offers_wed = @merchant.offers.active.wednesday_offers.order('created_at asc').to_a
    @offers_thu = @merchant.offers.active.thursday_offers.order('created_at asc').to_a
    @offers_fri = @merchant.offers.active.friday_offers.order('created_at asc').to_a
    @offers_sat = @merchant.offers.active.saturday_offers.order('created_at asc').to_a
    @offers_sun = @merchant.offers.active.sunday_offers.order('created_at asc').to_a

    @favorite = current_user.favorites.where(:merchant_id => @merchant.id).first if current_user

    @phone_number = @merchant.phone_format()
    @map_center = "#{@merchant.lat},#{@merchant.lon}"
    @offers = @merchant.offers
    respond_to do |format|
      format.html # show.html.erb
      format.json #{ render json: @merchant }
    end
  end

  # GET /merchants/new
  # GET /merchants/new.json
  def new
    @map_center = ''
    if current_city
      @map_center = "#{current_city.latitude},#{current_city.longitude}"
    end
    @merchant = Merchant.new
    object = @merchant
    respond_to do |format|
      format.html # new.html.erb
      format.mobile
      format.json { render json: object }
    end
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
    object = @merchant
    params[:city_name] = @merchant.city ? @merchant.city.name : ''
    @map_center = "#{@merchant.lat},#{@merchant.lon}"
  end

  # POST /merchants
  # POST /merchants.json
  def create
    begin
      loc=GoogleGeocoder.geocode(params[:merchant][:primary_address],:bias => current_country.code)
      params[:merchant][:primary_address] = loc.full_address
      params[:merchant][:lat] = loc.lat
      params[:merchant][:lon] = loc.lng
      loc.all.each { |e|
        if e.hash[:city]

          city = City.where(:name => e.hash[:city].strip).first
          if city

            params[:merchant][:city_id] = city.id
            #          session[:twilio_number] = city.country.twilio_number if city.country
            break
          end
        end
      }
    rescue
      res = GoogleGeocoder.reverse_geocode([params[:merchant][:lat].to_f, params[:merchant][:lon].to_f])
      params[:merchant][:primary_address] = res.full_address
      params[:merchant][:lat] = params[:merchant][:lat].to_f
      params[:merchant][:lon] = params[:merchant][:lon].to_f
      res.all.each { |e|
        if e.hash[:city]

          city = City.where(:name => e.hash[:city].strip).first
          if city

            params[:merchant][:city_id] = city.id
            #          session[:twilio_number] = city.country.twilio_number if city.country
            break
          end
        end
      }
    end

    @merchant = Merchant.new(params[:merchant])
    if params[:merchant][:phone]
      params[:merchant][:phone] = params[:merchant][:phone].strip.scan(/\d/).map { |n| n.to_i }.join()
    end
    if params[:merchant][:mon_start_time] != ""
      params[:merchant][:mon_start_time] = Time.parse(params[:merchant][:mon_start_time])
    end
    if params[:merchant][:tue_start_time] != ""
      params[:merchant][:tue_start_time] = Time.parse(params[:merchant][:tue_start_time])
    end
    if params[:merchant][:wed_start_time] != ""
      params[:merchant][:wed_start_time] = Time.parse(params[:merchant][:wed_start_time])
    end
    if params[:merchant][:thu_start_time] != ""
      params[:merchant][:thu_start_time] = Time.parse(params[:merchant][:thu_start_time])
    end
    if params[:merchant][:fri_start_time] != ""
      params[:merchant][:fri_start_time] = Time.parse(params[:merchant][:fri_start_time])
    end
    if params[:merchant][:sat_start_time] != ""
      params[:merchant][:sat_start_time] = Time.parse(params[:merchant][:sat_start_time])
    end
    if params[:merchant][:sun_start_time] != ""
      params[:merchant][:sun_start_time] = Time.parse(params[:merchant][:sun_start_time])
    end
    params[:merchant][:mon] = params[:merchant][:mon] == 'true' ? true : false
    params[:merchant][:tue] = params[:merchant][:tue] == 'true' ? true : false
    params[:merchant][:wed] = params[:merchant][:wed] == 'true' ? true : false
    params[:merchant][:fri] = params[:merchant][:fri] == 'true' ? true : false
    params[:merchant][:thu] = params[:merchant][:thu] == 'true' ? true : false
    params[:merchant][:sat] = params[:merchant][:sat] == 'true' ? true : false
    params[:merchant][:sun] = params[:merchant][:sun] == 'true' ? true : false
    @merchant.third_party_code = 'yacto'
    respond_to do |format|
      if @merchant.save
        if current_user.admin?
          current_user.update_attribute("merchant_id" ,@merchant.id)
        else
          current_user.update_attributes(:merchant_id => @merchant.id, :role_id => Role.where(:name => 'Merchant admin').first.id)
        end
        if params[:merchant][:merchant_type_id ] == 1 and params[:type_name ] != 'Default'
          UserMailer.confirm_merchant_type("New merchant type: " + params[:type_name ] + ' from google. link: ' + url_for(@merchant)).deliver
        end
        format.html { redirect_to '/', notice: t("merchant.create") }
        format.mobile { redirect_to '/', notice: t("merchant.create")}
        #        format.json { render json: @merchant, status: :created, location: @merchant }
      else
        format.html { render action: "new" }
        format.mobile { render action: "new" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /merchants/1
  # PUT /merchants/1.json
  def update
    address = params[:merchant][:primary_address] if  params[:merchant][:primary_address].present?
    address += ' , ' + params[:city_name] if params[:city_name].present?
    address += ' , ' + params[:merchant][:state_province_region] if params[:merchant][:state_province_region].present?
    address += ' ' + params[:merchant][:postal_code] if params[:merchant][:postal_code].present?
    address += ' , '  + params[:merchant][:country] if params[:merchant][:country].present?

    @merchant = Merchant.find(params[:id])
    puts(address)
    begin
      loc=GoogleGeocoder.geocode(address)
      params[:merchant][:primary_address] = loc.street_address
      params[:merchant][:lat] = loc.lat
      params[:merchant][:lon] = loc.lng
      params[:merchant][:postal_code] = loc.zip
      params[:merchant][:state_province_region] = loc.state
      puts loc.to_json
      loc.all.each { |e|
        if e.hash[:city]
  
          city = City.where(:name => e.hash[:city].strip,:country_iso_code_two_letters => loc.country_code).first
          if city
  
            params[:merchant][:city_id] = city.id
            #          session[:twilio_number] = city.country.twilio_number if city.country
            break
          end
        end
      }
    rescue
      res = GoogleGeocoder.reverse_geocode([params[:merchant][:lat].to_f, params[:merchant][:lon].to_f])
      params[:merchant][:primary_address] = res.full_address
      params[:merchant][:lat] = params[:merchant][:lat].to_f
      params[:merchant][:lon] = params[:merchant][:lon].to_f
      res.all.each { |e|
        if e.hash[:city]
  

app/helpers/merchants_helper.rb
module MerchantsHelper
  def merchant_open_time(merchant)
    if merchant.start_open_time
      "#{format_time(merchant.start_open_time)} - #{format_time(merchant.end_open_time, " ")}"
    else
      t("merchant.not_available")
     end
  end

  def merchant_social_string(merchant)
    "Check out #{merchant.name}, www.yacto.com/#{merchant.merchant_id}"
  end
end

app/views/merchants/edit.html.erb
<h1><%= t("form.editingclass", :class => "Merchant") %></h1>

<%#= render 'form' %>
<%= render 'image/form_upload' ,:object => @merchant %>
<%= link_to t("form.show"), @merchant %> |
<%= link_to t("form.back"), merchants_path %>

app/views/merchants/edit.mobile.erb
<div data-role="header" data-theme="e">
  <h1>Yacto</h1>
</div>
<%= render :partial => "shared/nav_home" %>
<h2><%= t("form.editingclass", :class => "Merchant") %></h2>
<div class="ui-body ui-body-d">
  <div class="box">
    <%= render 'form' %>
  </div>
</div>
<%= link_to t("form.show"), @merchant %> |
<%= link_to t("form.back"), merchants_path %>

app/views/merchants/index.mobile.erb
<div data-role="header" data-theme="e">
  <h1>Yacto</h1>
</div>
  <%= render :partial => "shared/nav_home" %>
<div data-role="content">
  <div class="content-primary">	
    <h3><%= t("form.listclasses", :classes => "merchants") %></h3>
    <ul data-role="listview" data-split-icon="gear" data-split-theme="d" style="margin-bottom: 20px;">
      <% @merchants.each do |merchant| %>
        <li>
          <a href="<%= merchant_path(merchant)%>">
            <div style="width: 120px; float: left;">
              <span class="<%= merchant.merchant_type.merchant_type %>"><%= merchant.merchant_type.merchant_type %></span>
              <h3 style="width: 120px;"><%= merchant.name  %></h3>
              <%= merchant.user_rating %>
            </div>
            <p style="white-space: normal;">
              <%= merchant.mobile_description %>
            </p>
          </a>
        </li>
      <% end %>
    </ul>


    <%= link_to t("form.newclass", :class => "Merchant"), new_merchant_path, "data-role" => "button", "data-theme" =>"e"%>

  </div>
</div>

app/views/merchants/new.html.erb
<h1><%= t("form.newclass", :class => "Merchant") %></h1>

<%= render 'form' %>

<%= link_to t("form.back"), merchants_path %>

app/views/merchants/new.mobile.erb
<div data-role="header" data-theme="e">
  <h1>Yacto</h1>
</div>
  <%= render :partial => "shared/nav_home" %>
<h2><%= t("form.newclass", :class => "Merchant") %></h2>
<div class="ui-body ui-body-d">

    <%= render 'form' %>

</div>
<%= link_to t("form.back"), merchants_path %>

app/views/merchants/show.html.erb
<script type="text/javascript">

  $(document).ready(function (){
    var latlng = new google.maps.LatLng(<%= @map_center %>);  
    var myOptions = {
      zoom: <%= @map_zoom ? @map_zoom : "10" %>,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      scrollwheel: false
    };
    map = new google.maps.Map(document.getElementById("map"), myOptions);

    var image = '/assets/markers/pin/image.png';
    verifyMarker = new google.maps.Marker({
      map: map,
      position: latlng,
      icon: image
    });
  });
</script>
<div id="map"></div>
<p>
  <b><%= t("merchant.name") %>:</b>
  <%= @merchant.name %>
</p>

<p>
  <b><%= t("merchant.desc") %>:</b>
  <%= @merchant.mobile_description %>
</p>

<p>
  <b><%= t("merchant.paddress") %>:</b>
  <%= @merchant.primary_address %>
</p>

<p>
  <b><%= t("merchant.userrating") %>:</b>
  <%= @merchant.user_rating %>
</p>

<p>
  <b><%= t("merchant.type") %>:</b>
  <%= @merchant.merchant_type.merchant_type %>
</p>



<%= link_to t("form.edit"), edit_merchant_path(@merchant) %> |
<%= link_to t("form.back"), merchants_path %>

app/views/merchants/sms_request.html.erb
<%= form_tag("/merchants/sms_request", :method => "get") do %>
  <p>
    <%= label_tag(:From, "Phone number:") %>
    <%= text_field_tag(:From) %>
  </p>
  <p>
    <%= label_tag(:Body, "Sms request:") %>
    <%= text_area_tag(:Body,nil, :cols => 50, :rows => 10) %>
  </p>
  <%= submit_tag("Sent") %>
<% end %>

app/views/merchants/sms_request.mobile.erb
<%= form_tag("/merchants/sms_request", :method => "get") do %>
  <p>
    <%= label_tag(:From, "Phone number:") %>
    <%= text_field_tag(:From) %>
  </p>
  <p>
    <%= label_tag(:Body, "Sms request:") %>
    <%= text_area_tag(:Body) %>
  </p>
  <%= submit_tag("Sent") %>
<% end %>

app/views/merchants/survey.html.erb
<div>
  <form action="/merchants/survey" method="get" novalidate="novalidate">
    City: <input type="text"  name="city" value ="<%= params[:city] %>" class="merchant_survey_city">
    <button type="submit" class="reset_password">Search</button>
  </form>

</div>
<table id="merchant_list">
  <tr>

    <th>Country</th>
      <th> &nbsp &nbsp</th>
    <th>City</th>

    <th>Merchant number</th>
    <th>Offer number</th>

  </tr>


<% @merchants.each do |merchant| %>
  <tr>

    <td><%= merchant.country_name %></td>
    <td>  </td>
    <td><%= link_to merchant.name, :action => "survey_city", :id => merchant.id %></td>

    <td><%= merchant.merchant_count %></td>
    <td><%= merchant.offer_count %></td>

  </tr>
<% end %>
</table>


  <%= will_paginate @merchants %>

app/views/merchants/survey_city.html.erb
<h1>Each Source</h1>
<table id="source_group_merchants">
  <tr>

    <th>Country</th>
    <th> &nbsp &nbsp</th>
    <th>City</th>
    <th>Source</th>
    <th>Merchant number</th>
    <th>Offer number</th>

  </tr>


  <% @source_group_merchants.each do |merchant| %>
      <tr>

        <td><%= merchant.country_name %></td>
        <td>  </td>
        <td><%= merchant.name %></td>
        <td><%= merchant.third_party_code %></td>
        <td><%= merchant.merchant_count %></td>
        <td><%= merchant.offer_count %></td>

      </tr>
  <% end %>
</table>
<h1>Each Type</h1>
<table id="type_group_merchants">
  <tr>

    <th>Country</th>
    <th> &nbsp &nbsp</th>
    <th>City</th>
    <th>Source</th>
    <th>Type</th>
    <th>Merchant number</th>
    <th>Offer number</th>

  </tr>


  <% @type_group_merchants.each do |merchant| %>
      <tr>

        <td><%= merchant.country_name %></td>
        <td>  </td>
        <td><%= merchant.name %></td>
        <td><%= merchant.third_party_code %></td>
        <td><%= merchant.merchant_type_name %></td>
        <td><%= merchant.merchant_count %></td>
        <td><%= merchant.offer_count %></td>

      </tr>
  <% end %>
</table>