config/routes.rb
Yacto::Application.routes.draw do

  resources :error_messages

  get 'cities/search' => "cities#search"
  resources :cities

  resources :countries

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations" ,:omniauth_callbacks => "omniauth_callbacks"} do
    get '/users/auth/:provider' => 'omniauth_callbacks#twitter'
    get '/users/sign_out' => "devise/sessions#destroy"
   
  end
  get "users/session_user"
  get "users/get_session"
  get "offers/dashboard"
  get "start_page/index"
  get "start_page/index3"
  get "start_page/offer"
  get "start_page/page03"
  get "start_page/offer03"
	%w(about_us blog contact_us our_partners terms_and_conditions privacy business_owners how_it_works_merchants how_it_works_consumers).each	do |page|
		get page,  :controller => "static_pages",:action => page
	end

  get "home/ajax_twitter_on"
  get "home/ajax_twitter_off"
  get "home/ajax_gplus_on"
  get "home/ajax_gplus_off"
  get "home/ajax_facebook_on"
  get "home/ajax_facebook_off"
	get "home/about_us"
  get "offers/ajax_favorite"
  get "offers/ajax_unfavorite"
  get "merchants/ajax_favorite"
  get "merchants/ajax_unfavorite"
  get "offers/ajax_lonlat"
  get "offers/require_sign_in"
  post "home/lookup_address"
  post "offers/unique_email"
  post "offers/create_offer"
  post "offers/get_google_places"
  post "offers/get_business_detail"
  post "offers/post_social_network_offer"
  post "offers/post_persional_detail"
  get 'home/autocomplete'
  get 'home/autocomplete_address'
  get "offers/filter_to_offers"
  get 'offers/redirect_to_offers'
  get 'offers/get_more_product'
  get 'offers/filter'
  get "merchants/sms_request"
  get "merchant_types/top_lvl"
  get 'offers/list_detail'
  get "merchants/call"
  get "offers/nearby"
  get "offers/ajax_time"
  get "offers/ajax_distance"
  get "offers/ajax_offer_group"
  get "offers/set_location"
  get "merchants/survey"
  get "merchants/survey_city"
  get "merchants/survey_source"
  post "merchants/search_google_place"
  match "merchants/admin" => "merchants#admin"

  put 'users/generate_code/:id' => "users#generate_code"
  put 'offers/update_repeat_day/:id' => "offers#update_repeat_day"
  put 'offers/update_local_end_day/:id' => "offers#update_local_end_day"
  put 'merchants/update_repeat_merchant/:id' => "merchants#update_repeat_merchant"
  put 'merchants/update_active/:id' => "merchants#update_active"
  put 'offers/update_merchant_type/:id' => 'offers#update_merchant_type'

  put "users/account_setting/:id"  => "users#account_setting"

  match "users/show" => "users#show"

  resources :offers, :offer_insertions, :merchant_types

  resource :location, :only => [:show]
  resources :favorites, :only => [:create, :index, :destroy]

  resource :dashboard, :only => [:show] do
    get "offers", :on => :member
  end

  resource :bb, :only => :show, :controller => "backbone"

  resources :merchants do
    collection do
      post  "search"
      post "sms_request"
     
    end
  end
  match ':merchant_id' => "users#index", :as => :merchant_details
  
  resources :users do
    member do
      get "toggle_offer", "change_recurrence"
      
    end
    collection do
      get "ajax_sub_types"
      post "new_employee"
      post "new_merchant_offer"
    end
  end

  root :to => 'home#index'
  get "home/index"
  resources :merchant_photos

end

app/helpers/offers_helper.rb
module OffersHelper
  def offers_saved
    return false if cookies[:offers_key].blank? 
    current_key = [params[:lat], params[:lon], params[:merchant_type_id]]
    current_key == JSON.parse(cookies[:offers_key])
  end

  def offer_time(offer)
    if offer.all_day?
      t("offer.all_day")
    else
      "#{format_time(offer.start_time)} - #{format_time(offer.end_time, " ")}"
    end
  end

  def offer_icon_class(offer)
    offer.merchant.merchant_type.marker_image.split(".")[0]
  end

  def format_time(time, default = "")
    time ? time.strftime('%I:%M%P').gsub(/^0/,'') : default
  end

  def format_third_party_code(offer)
    offer.third_party_code.gsub("_", ' ').split.map(&:capitalize).join(' ')
  end

  def new_buy_via_label(offer)
    case offer.third_party_code
    when Offer.third_party_code_for(:factual), Offer.third_party_code_for(:eight_coupons),Offer.third_party_code_for(:yelp)
      "Buy Coupon at #{format_third_party_code(offer)}"
    when Offer.third_party_code_for(:vouchercodes)
      "Get Voucher at #{format_third_party_code(offer)}"
    when Offer.third_party_code_for(:gotime),Offer.third_party_code_for(:drinkowl), Offer.third_party_code_for(:yacto) 
      "Use now at #{format_third_party_code(offer)}!"
    when Offer.third_party_code_for(:toptable), Offer.third_party_code_for(:opentable), Offer.third_party_code_for(:booktable)
      "Reserve at #{format_third_party_code(offer)}"
    else 
      "Buy Coupon"
    end
  end

  def buy_via_link_label(offer)
    if offer.third_party_code and offer.link_present? and offer.description
      "Buy via " + format_third_party_code(offer)
    else
      if offer.link_present? and offer.merchant.try(:third_party_merchant_type) and offer.merchant.third_party_merchant_type.merchant_type_id and offer.description
        "Buy via 8coupons "
      else
        if offer.link_present? and offer.description 
          "Buy "
        end
      end
    end
  end
  
  def buy_message(offer, class_name)
    html = ""
    if  offer.third_party_code and offer.link and offer.link.strip != '' and offer.description
    
      if offer.third_party_code == "vouchercodes"
        html << offer.description[0,140 - (t('offer.get_voucher_through') + offer.third_party_code.gsub("_", ' ').split.each{|i| i.capitalize!}.join(' ')).length ]
        html << "#{link_to( t('offer.get_voucher_through') + offer.third_party_code.gsub("_", ' ').split.each{|i| i.capitalize!}.join(' '), offer.link ,:class => class_name ? class_name : nil)}"
      else
        html << offer.description[0,140 - (t('offer.buy_via') + offer.third_party_code.gsub("_", ' ').split.each{|i| i.capitalize!}.join(' ')).length ]
        html << "#{link_to( t('offer.buy_via')  + offer.third_party_code.gsub("_", ' ').split.each{|i| i.capitalize!}.join(' '), offer.link ,:class => class_name ? class_name : nil)}"
      end
    else
      if offer.link and offer.link.strip != '' and offer.merchant.third_party_merchant_type and offer.merchant.third_party_merchant_type.merchant_type_id and offer.description
        html << offer.description[0,140 - (t('offer.buy_via') + "8coupons ").length ] 
        html <<  "#{link_to( t('offer.buy_via') + "8coupons ", offer.link,:class => class_name ? class_name : nil )}"
      else
        if offer.link and offer.link.strip != '' and offer.link != 'http://dummy-link.com' and offer.description
          html << offer.description[0,140 - t('offer.buy').length ] 
          html <<  "#{link_to(  t('offer.buy'), offer.link, :class => class_name ? class_name : nil)}"
        else
          html <<  (offer.description != nil ? offer.description : "")
        end
      end
    end
  end

  def offer_sms_body(offer)
    'Check out this great limited-time special at ' << (offer.merchant.try(:name) ? offer.merchant.name : '')  << ' : www.yacto.com/' << offer.merchant.try(:merchant_id) << ' ' << (offer.description ? offer.description : '')
  end

  def offer_email_link(offer)
    "mailto:?subject=Yacto&body=Check out this great limited-time special at #{offer.merchant.name} : www.yacto.com/#{offer.merchant.merchant_id} #{offer.description}"
  end

  def offer_twitter_str(offer)
    return "" if offer.nil?
    twitter_str = "Check out this limited-time special I found on Yacto www.yacto.com/"+(offer.merchant.try(:merchant_id) ? offer.merchant.merchant_id : "")+" "+ (offer.description ? offer.description : "")
    if twitter_str.length > 137
      twitter_str = twitter_str[0,136] + "..."
    end
    twitter_str
  end
  
  def format_active(id)
    if id == 1
      return "Active"
    elsif id == 2
      return "Stop"
    end
  end

end

app/views/offers/_offer.mobile.erb
<div class="list_item_wrapper">
  <div class="scroller_item list_item clearfix">
    <div class="offer-small-details">
      <a href="<%= backbone_merchant_path(offer.merchant) %>"><div class="offer-type <%= offer_icon_class(offer) %>"></div></a>
      <div class="offer-opening-hours">
        <%#<span class="opening">9:00</span> <span class="closing">23:00</span>%>
        <% if offer.period(@now_time) %>
          <span style="color:red;">
            <%= offer.period(@now_time)  %> <%=t("offer.minute")%>
          </span>
        <% else %>
          <%= offer_time(offer) %>
        <% end %>
      </div>
    </div>
    <div class="offer-description">
      <h2 class="offer-name">
        <a class="offer-name-link" href="<%= backbone_merchant_path(offer.merchant) %>"><%= offer.merchant.name %></a>
      </h2>

      <p class="offer-text">
        <a class="offer-description-link" href="<%= backbone_merchant_path(offer.merchant) %>"><%= offer.description %></a>
      </p>
    </div>
    <div class="offer-action">
      <a href="<%= selected_nearby_path_with_params(offer.id) %>" class="offer-action-button"></a>
    </div>
    <span class="offer-distance"><%= number_with_precision(offer.distance_from(@res, :units=>:miles),:precision => 1)  %>mi</span>
  </div>
</div>

app/views/offers/nearby.mobile.backup.erb
<%= javascript_include_tag "jcarousellite"%>
<script>!window.jQuery && document.write(unescape('%3Cscript src="/lib/jquery.js"%3E%3C/script%3E'));</script>
<script>
  $(document).ready(function() {
    
    $('div#closer').live('click', function () {
      console.log('close');
      
      $('.container').html('');
      
      return true;
    });

    
    $('div.click').live('click', function () {
      console.log($(this));
      var link = $(this).find('a:first');
      if (link) {
        if ($(link).attr('data-ajax') == "false") {
          document.location = $(link).attr('href').toString();
        } else {
          $.mobile.changePage($(link).attr('href').toString());
        }
      }
    });
  });
    

</script>

<div data-role="page" style="padding-left: 0;padding-right: 0px;" id="index_page">
  <div data-role="header" data-position="fixed" style="border-color: #cccccc;">
    <header class="mobile-header" style="position: absolute;width: 100%">
      <nav class="clearfix">
        <a class="mobile-nav-item offers" data-role="none" rel="external" href="<%= offers_path_with_params %>"><div></div></a>
        <a class="mobile-nav-item nearby active" data-role="none" rel="external" href="<%= nearby_path_with_params %>"><div></div></a>
        <a class="mobile-nav-item logo"><div></div></a>
        <% if current_user %>
          <a class="mobile-nav-item favorites" data-role="none" rel="external" href="<%= favorites_path_with_params %>"><div></div></a>
        <% else %>
          <a class="mobile-nav-item favorites" data-role="none" rel="external" href="#" id="popupbut"><div></div></a>
        <% end %>
        <a class="mobile-nav-item filters" href="<%= new_filters_path_with_params %>" data-ajax="false" id="filter_dialog"><div></div></a>
      </nav>
    </header>
  </div>
  <script type="text/javascript">

    $(document).ready(function (){

<% if params[:distance] %>
      var radius = <%= params[:distancce].to_f %>;
      var z = Math.round(14 - Math.log(<%=  params[:distance].to_f %> )/Math.LN2);
<% else %>
      var radius = 1;
      var z = Math.round(14 - Math.log(1)/Math.LN2) ;
<% end %>

    var latlng = new google.maps.LatLng(<%= @my_location %>);
    var image = '/assets/markers/pin/image.png';
    var myOptions = {
      zoom: z,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      scrollwheel: false

    }

    var map = new google.maps.Map(document.getElementById("map_show"), myOptions);
    var marker = new google.maps.Marker({
      position: latlng,
      map: map,
      icon: image

    });

<% if @merchants %>
      var points = <%= raw @merchants.to_json(:include => :merchant_type) %>;


      for(var i = 0; i < points.length ;i++) {
        markers(points[i],map,google);
      }


<% end %>
    var populationOptions = {
      map: map,
      center:  latlng,
      fillOpacity: 0,
      strokeOpacity:0,
      radius: radius * 1609.344
    };

    var circle = new google.maps.Circle(populationOptions);

  });

function markers(point,map,google){
var new_point = new google.maps.LatLng(point.lat, point.lon );
                     var image = '/assets/markers/' +  (point.marker_image ? point.marker_image : 'look.png');
                     var marker_point = new google.maps.Marker({
                                        position: new_point,
                                        map: map,
                                        icon: image,
                                        url: '/merchants/' + point.id
                                      });
      google.maps.event.addListener(marker_point, 'click', function() {
    $.ajax({
        type: 'GET',
        url: '/offers/ajax_offer_group',
        data: 'id=' + point.id + '&lat=<% params[:lat] %>&lon=<%=params[:lon]%>&merchant_type_id=<%=params[:merchant_type_id]%>&favorite=<%=params[:favorite]%>&time=<%=params[:time]%>&distance=<%=params[:distance]%>',
        success: function(msg){
          $('.container').html(msg);
          $('.container').show();
          return false;
        },
        error: function(e){

          return false;
        }
      });
    });
  }
  </script>

  <div id="nearby_content">
    <div class="container">

    </div>
    <script type="text/javascript">
<%  if cookies[:first_time] != 'true' %>
    var mobileDemo = { 'center': '57.7973333,12.0502107', 'zoom': 5 };
    $('#index_page').live('pageinit', function() {
      demo.add('index_page', function() {

        $('#map_show').gmap({'center': mobileDemo.center, 'zoom': 5 , 'disableDefaultUI':true, 'callback': function(map) {
            var self = this;
            self.watchPosition(function(position, status) {
              if ( status === 'OK' ) {

                var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                $.ajax({
                  type: "GET",
                  url: "<%= offers_ajax_lonlat_path %>",
                  data: "lon=" +  position.coords.longitude + "&lat=" + position.coords.latitude,

                  success: function(data){
                    window.location.reload();
                    return false;
                  },
                  error: function(msg){

                    console.log("There is an error : can't get data");
                    return false;
                  }
                });
                if ( !self.get('markers').client ) {
                  self.addMarker({ 'id': 'client', 'position': latlng, 'bounds': true });
                } else {
                  self.get('markers').client.setPosition(latlng);
                  //-try to add circle for mobile---self.set('clientPosition', new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
                  //-try to add circle for mobile---self.addShape('Circle', { 'strokeWeight': 0, 'fillColor': "#008595", 'fillOpacity': 0.25, 'center': self.get('clientPosition'), 'radius': 15, clickable: false });
                  map.panTo(latlng);
                }
              }
            });
          }});
      }).load('index_page');
    });

<% end %>

    </script>
    <div class="paddedContent">
      <div id="map_show" style="width: 100%; height: 100%;"></div>
    </div>

    <div id="info"></div>
  </div>
</div>

app/views/offers/new.html.erb
<h1><%= t("form.newclass", :class => "offer") %></h1>

<%= render 'form' %>

<%= link_to t("form.back"), offers_path %>

app/views/offers/show.mobile.erb
<%= javascript_include_tag "infobox" %>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
  {"parsetags": "explicit"}
</script>
<script type="text/javascript" src="https://connect.facebook.net/en_US/all.js">

</script>
<% content_for :head do %>
<meta charset="utf-8" />
 <meta name="title" content="aaaaa" />
  <meta name="description" content="aaaaaw2244" />
    <meta name="description" content ="Check out this great limited-time special at <%= @offer.merchant.name %> : www.yacto.com/<%=  @offer.merchant.merchant_id %> <%=  @offer.description %>" />
    <meta property="og:title" content="Yacto"/>
    <meta property="og:type" content="website" />
    <meta property="og:url" content="Check out this great limited-time special at <%= @offer.merchant.name %> : www.yacto.com/<%=  @offer.merchant.merchant_id %> <%=  @offer.description %>" />
    <meta property="og:site_name" content="Yacto"/>
    <meta property="og:description" content="Check out this great limited-time special at <%= @offer.merchant.name %> : www.yacto.com/<%=  @offer.merchant.merchant_id %> <%=  @offer.description %>"/>

<% end %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div data-role="page" style="padding-left: 0;padding-right: 0px;">
  <div data-role="header" data-theme="c" style="height: 45px;">
    <div style="width: 41.25%;float: left;">
      <fieldset  data-role="controlgroup" data-type="horizontal" style=" height: 28px;float: left; margin-left: 3px; margin-top: 3px;">
        <input width="54px" height="26px" type="radio" name="radio_view" id="radio-choice-c" value="10" <%= 'checked = "true"' if params[:radio_view] == "10"  %>   />
        <label class="text-overflow" for="radio-choice-c" style=" width: 54px; height: 30px;font-size: 9px; text-overflow: clip;">WITHIN</br>10MI</label>
        <input width="54px" height="26px" type="radio" name="radio_view" id="radio-choice-d" value="1"  <%= 'checked = "true"' if params[:radio_view] == "1"  %> />
        <label  class="text-overflow" for="radio-choice-d" style=" width: 54px;height: 30px; font-size: 9px;">WITHIN</br>1MI</label>
      </fieldset>
    </div>
    <div style="width: 17.5%;float: left; padding-top: 7px; text-align: center; ">
      <%= image_tag("mobile/logo.png")  %>
    </div>
    <div style="width: 41.25%;float: left;">
      <fieldset data-role="controlgroup" data-type="horizontal" style="float: right; height: 28px;margin-right: 3px; margin-top: 3px;">
        <input width="54px" height="26px" type="radio" name="radio_view" id="radio-choice-e" value="3" <%= 'checked = "true"' if params[:radio_view] == "3"  %>/>
        <label class="text-overflow" for="radio-choice-e" style="width: 54px; height: 30px;font-size: 9px;text-overflow: clip;">WITHIN </br> 3HRS</label>
        <input height="26px" type="radio" name="radio_view" id="radio-choice-f" value="all" <%= 'checked = "true"' if params[:radio_view] == "all"  %> />
        <label class="text-overflow" for="radio-choice-f" style="height: 30px;font-size: 9px;text-overflow: clip;">All </br> OFFERS</label>
      </fieldset>
    </div>
  </div>

<%#= render :partial => "shared/nav_home" %>
  <div data-role="content" style="padding-left: 0;padding-right: 0px; padding-top: 1px;">
    <div class="content-primary">
      <script type="text/javascript">

      $(document).ready(function (){
        $('#favorite').click(function() {

          $.ajax({
            type: "GET",
            url: "ajax_favorite",
            data: "id=" +  "<%= @offer.id %>",

            success: function(data){
              return false;
            },
            error: function(msg){
              console.log("There is an error : can't get data");
              return false;
            }
          });
        });
      });
      </script>
      <ul data-role="listview" style="margin-left: 0; margin-right: 0px;">
        <li style="border: none; background: none; padding: 0;">
          <div style="float: left;  width: 103px; padding-bottom:20px;border-right: 1px solid <%=  @offer.merchant ? @offer.merchant.merchant_type.color : '#564ea1' %>">
            <div style=" text-align: center; height: 15px;background-color: <%=  @offer.merchant ? @offer.merchant.merchant_type.color : '#564ea1' %>">
              <%= image_tag("mobile/"+( @offer.merchant ? @offer.merchant.merchant_type.image : ''),:style => "width :15px; height:15px;") %>
            </div>

            <p style="color: #202020;font-size: 12px;font-weight: bold"><%= @offer.name %></p>

            <span class="format_time"><%= @offer.start_time ? @offer.start_time.strftime('%I:%M%P') : '' %> - <%= @offer.end_time ? @offer.end_time.strftime('%I:%M%P') : ' '%></span>
            </br>
            <span class="format_time"> 
                <%= number_with_precision(@offer.distance_from(@res, :units=>:miles),:precision => 2)  %>mi

            </span>
            <span>
              <% if current_user %>
                <%= link_to(image_tag("mobile/star_mini.png"),"#",:id => 'favorite'+ @offer.id.to_s )%>
              <%  else %>
                <%= link_to(image_tag("mobile/star_mini.png"),"#",:id => 'popupbut')%>
              <% end %>
            </span>
          </div>
          <div style="text-align: right; height: 16px; padding-right: 3px;margin-top: 15px">
            <div class="btn_pre"> <span><a  href="#" data-role="none" >></a></span></div>
            <div class="btn_next"><span><a  href="#" data-role="none" ><</a></span></div>
          </div>
          <p style="white-space: normal; padding: 0px 5px; color: #202020;font-size: 11px;line-height:160%;">
            <%= @offer.description %>
          </p>   
        </li>
      </ul>
      <div style=" margin: 0 5px;">
        <div class="social">
          <div style="padding-top: 7px;">
            <div style="width: 13.333%">
              <%= image_tag("mobile/sms.png",:id => 'send_sms',:style => "cursor: pointer;")%>
            </div>

            <div style="margin-left: -2px; width: 13.333%">
              <%= image_tag("mobile/email_black.png",:id => 'send_mail',:style => "cursor: pointer;")%>
            </div>

            <div style="margin-left: -1px; margin-top: -2px">
              <a name="fb_share" type="button_count" href="http://www.facebook.com/sharer.php" share_url='' height="24"> share_url="beerfortextbooks.com"><span class="FBConnectButton FBConnectButton_Small" style="cursor: pointer;"><span class="FBConnectButton_Text">
    Share</span></span></a>
              <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
            </div>

            <div style="margin-left: -1px;">
                 <span style="padding-right: 15px;"> <a href="https://mobile.twitter.com/share" class="twitter-share-button" data-url="<%= url_for(@offer) %>" data-text="I like <%= @offer.name %>,check it out! <%= url_for(@offer)%>" >Tweet</a></span>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>

            <div style="margin-left: -1px; border: none; width: 13.333%">
              <span id="plusContent"></span>
              <script>
              var qrCode = 'A123456';
              var googleShareLink = "<g:plusone size='medium' id='shareLink' class='shareLink'  annotation='none' href='" + '<%= url_for(@offer) %>' + "?qrCode="+qrCode+"' callback='countGoogleShares'></g:plusone>";
              $("#plusContent").html(googleShareLink);
              gapi.plusone.go("plusContent");
              </script>
            </div>

          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">

    $(document).ready(function (){
      var latlng = new google.maps.LatLng(<%= @map_center %>);  
      var myOptions = {
        zoom: <%= @map_zoom ? @map_zoom : "10" %>,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        scrollwheel: false
      }

      var map = new google.maps.Map(document.getElementById("map_show"), myOptions);
      var boxText = document.getElementById("info");
      boxText.style.cssText = "margin-top: 14px;";
      boxText.innerHTML = '<div id ="infowindow" class ="downarrowdiv"><div class="div_left">' +'<%= image_tag("markers/icon_look.png",:style =>"")%>' + '</div>' + '<div class="format_text_popup_name">' + '<%= @offer.name %>' +'</div><div class="format_text_popup_address">' +'<%= @offer.primary_address %>' + '</div>'  +'<div class="div_right" style="z-index: 9999;">' + '<%= link_to(image_tag("markers/icon_next.png"),merchant_path(@offer.merchant),:style => "z-index:9999;")%>' + '</div></div>' ;
      
      var myOptions = {
        id: "infoBox"
        ,content: boxText
        ,disableAutoPan: true
        ,maxWidth: 0
        ,pixelOffset: new google.maps.Size(-135, -98)
        ,zIndex: 100
        ,boxStyle: { 
<%#*background: "url('/assets/markers/bg_info.png') no-repeat"%>
      opacity: 0.75
      ,width: "260"
      ,height: "47px"
      ,border: "none"
    }
    ,closeBoxMargin: "0px 2px 2px 2px"
    ,closeBoxURL: "http://www.google.com/intl/en_us/mapfiles/close.gif"
    ,infoBoxClearance: new google.maps.Size(1, 1)
    ,isHidden: false
    ,pane: "floatPane"
    ,enableEventPropagation: false
  };
         
        
  var myIcon = new google.maps.MarkerImage('/assets/markers/<%= @offer.merchant.merchant_type.marker_image %>', null, null, null, new google.maps.Size(40,50));
    
  var image = '/assets/markers/<%= @offer.merchant.merchant_type.marker_image %>';
<%#*verifyMarker = new google.maps.Marker({%>
<%#*map: map,%>
<%#*position: latlng,%>
<%#*icon: image%>
<%#*});%>
  var marker = new google.maps.Marker({
    position: latlng,
    map: map,
    icon: image
  });
  var infowindow = new InfoBox(myOptions);

<%#*var infowindow = new google.maps.InfoWindow();%>
<%#*infowindow.setSize(google.maps.Size(50,32));%>
<%#*infowindow.setContent("<div>Content goes here</div>");%>
<%#*infowindow.setPosition(marker.getPosition());%>
<%#*infowindow.set("isdomready", false);%>
<%#*infowindow.boxClass = "infowin-content";%>
  infowindow.open(map,marker);
  google.maps.event.addListener(marker, 'click', function() {
    console.log("click");
    infowindow.open(map,marker);
         
  });
  
 
});
    </script>
    <div id="map_show" style="margin-top: 45px;"></div>
    <div id="info"></div>
    <% if can? :manage, @offer %>
      <div data-role="footer" data-position="fixed" data-theme="c">
        <div data-role="navbar" data-iconpos="top">
          <ul>
            <li><%= link_to t("form.edit"), edit_offer_path(@offer),"data-icon" => "gear" %> </li>
            <li><%= link_to t("form.back"), offers_path, "data-icon" => "back" %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <div data-role="footer"  data-position="fixed" id ="footer" class="ui-grid-c" data-theme="c">
        <div class="ui-block-a"><a href="/offers"><div id ="offer"></div></a></div>
        <div class="ui-block-b"><a class="active" href="/offers?filter_nearby=1"><div id ="nearby"></div></a></div>
        <div class="ui-block-c"><a href="/offers?favorite=1" id="favorite_all"><div id ="favorite"></div></a></div>
        <div class="ui-block-d"><a href="/offers/filter" data-ajax="false"  ><div id ="filters"></div></a></div>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function (){
  var x = parseInt($("div#info").height()) - 44;
  $("div#info").css('margin-top','-' + x.toString() + 'px');
  console.log( $("div.infoBox").height());
});
</script>